project_name             = "ecs-alb-login-server"
image_name               = "public.ecr.aws/m6h0f1x7/ecs_alb_login_server:latest"
cw_metric_resolution_min = "60"
task_cpu                 = "256"
task_memory              = "512"
container_port           = "3000"
internet_gateway_id      = "igw-09c986cbd6156b8ec"
